// Exact SV_APPT whitelist from scripts/dealervault/dealertrack_file_types.txt.
export const SV_APPT_FIELDS = Object.freeze([
  "File Type",
  "DV Dealer ID",
  "Vendor Dealer ID",
  "DMS Type",
  "Appointment Number",
  "Appointment Date",
  "Appointment Time",
  "Appointment Create Date",
  "RO Number",
  "Last RO Miles",
  "Last RO Date",
  "Promise Date",
  "Promise Time",
  "Cause",
  "Complaint",
  "Comment",
  "Operation Code",
  "Operation Code Description",
  "Recommended Operation Code",
  "Recommended Operation Code Description",
  "Service Advisor Number",
  "Service Advisor Name",
  "Sale Type",
  "Waiting Flag",
  "Loaner Flag",
  "Alternate Transportation",
  "Estimate Time",
  "Estimate Amount",
  "Tag Number",
  "VIN",
  "Year",
  "Make",
  "Model",
  "Model Number",
  "Appointment Mileage",
  "Description",
  "Exterior Color",
  "Stock Number",
  "Transmission",
  "Engine Configuration",
  "Trim",
  "Engine Number",
  "Chassis Number",
  "License Plate Number",
  "Delivery Date",
  "Delivery Mileage",
  "In Service Date",
  "VIN Explosion Year",
  "VIN Explosion Make",
  "VIN Explosion Model",
  "VIN Explosion Trim",
  "VIN Explosion Transmission Type",
  "VIN Explosion Fuel Type",
  "VIN Explosion Engine Size",
  "VIN Explosion GVW Range",
  "Customer Number",
  "Full Name",
  "Salutation",
  "First Name",
  "Middle Name",
  "Last Name",
  "Suffix",
  "Address Line 1",
  "Address Line 2",
  "City",
  "State",
  "Zip",
  "County",
  "Home Phone",
  "Cell Phone",
  "Work Phone",
  "Work Extension",
  "Email 1",
  "Email 2",
  "Email 3",
  "Birth Date",
  "Individual/Business Flag",
  "Opt Out",
  "Block Email",
  "Block Phone",
  "Block Mail",
  "Language",
  "Customer Create Date",
  "Customer Last Activity Date",
  "CASS_STD_LINE1",
  "CASS_STD_LINE2",
  "CASS_STD_CITY",
  "CASS_STD_STATE",
  "CASS_STD_ZIP",
  "CASS_STD_ZIP4",
  "CASS_STD_DPBC",
  "CASS_STD_CHKDGT",
  "CASS_STD_CART",
  "CASS_STD_LOT",
  "CASS_STD_LOTORD",
  "CASS_STD_URB",
  "CASS_STD_FIPS",
  "CASS_STD_EWS",
  "CASS_STD_LACS",
  "CASS_STD_ZIPMOV",
  "CASS_STD_Z4LOM",
  "CASS_STD_NDIAPT",
  "CASS_STD_NDIRR",
  "CASS_STD_LACSRT",
  "CASS_STD_ERROR_CD",
]);
