// Exact SV whitelist from scripts/dealervault/dealertrack_file_types.txt.
export const SV_FIELDS = Object.freeze([
  "File Type",
  "DV Dealer ID",
  "Vendor Dealer ID",
  "DMS Type",
  "RO Number",
  "Open Date",
  "Close Date",
  "Service Advisor Number",
  "Service Advisor Name",
  "RO Department",
  "RO Store",
  "Appointment Date",
  "Appointment Flag",
  "Appointment Number",
  "Appointment Department",
  "Accounting Make",
  "Pickup Date",
  "Pickup Time",
  "Post Time",
  "Promise Date",
  "Promise Time",
  "Payment Method",
  "RO Status",
  "Print Time",
  "Salesman Name",
  "Salesman Number",
  "Service Contract Name",
  "Service Contract Number",
  "Tag Number",
  "Warranty Expiration Date",
  "Warranty Expiration Miles",
  "Total Cost",
  "Total Sale",
  "Customer Total Cost",
  "Customer Total Sale",
  "Customer Labor Cost",
  "Customer Labor Sale",
  "Customer Parts Cost",
  "Customer Parts Sale",
  "Customer Misc Cost",
  "Customer Misc Sale",
  "Customer Gas/Oil/Grease Cost",
  "Customer Gas/Oil/Grease Sale",
  "Customer Sublet Cost",
  "Customer Sublet Sale",
  "Warranty Total Cost",
  "Warranty Total Sale",
  "Warranty Labor Cost",
  "Warranty Labor Sale",
  "Warranty Parts Cost",
  "Warranty Parts Sale",
  "Warranty Misc Cost",
  "Warranty Misc Sale",
  "Warranty Gas/Oil/Grease Cost",
  "Warranty Gas/Oil/Grease Sale",
  "Warranty Sublet Cost",
  "Warranty Sublet Sale",
  "Internal Total Cost",
  "Internal Total Sale",
  "Internal Labor Cost",
  "Internal Labor Sale",
  "Internal Parts Cost",
  "Internal Parts Sale",
  "Internal Misc Cost",
  "Internal Misc Sale",
  "Internal Gas/Oil/Grease Cost",
  "Internal Gas/Oil/Grease Sale",
  "Internal Sublet Cost",
  "Internal Sublet Sale",
  "Total Labor Cost",
  "Total Labor Sale",
  "Total Parts Cost",
  "Total Parts Sale",
  "Total Misc Cost",
  "Total Misc Sale",
  "Total Gas/Oil/Grease Cost",
  "Total Gas/Oil/Grease Sale",
  "Total Sublet Cost",
  "Total Sublet Sale",
  "Total Misc Code Sale",
  "Total Tax",
  "Customer Total Tax",
  "Warranty Total Tax",
  "Internal Total Tax",
  "Operation Codes",
  "Operation Code Descriptions",
  "Tech Labor Line",
  "Tech Number",
  "Tech Name",
  "Upsell",
  "Labor Cause",
  "Labor Complaint",
  "Labor Correction",
  "Labor Comments",
  "Recommended Operation Codes",
  "Recommendations",
  "Operation Line Number",
  "Operation Sale Types",
  "Operation Line Cost",
  "Operation Line Sale",
  "Labor Cost",
  "Labor Sale",
  "Parts Cost",
  "Parts Sale",
  "Misc Cost",
  "Misc Sale",
  "Gas/Oil/Grease Cost",
  "Gas/Oil/Grease Sale",
  "Sublet Cost",
  "Sublet Sale",
  "Labor Tech Hours",
  "Labor Bill Hours",
  "Labor Tech Rate",
  "Labor Bill Rate",
  "Parts Labor Line Number",
  "Parts Line Number",
  "Parts Sale Type",
  "Part Number",
  "Part Description",
  "Part Quantity",
  "Parts Unit Cost",
  "Parts Unit Sale",
  "VIN",
  "Year",
  "Make",
  "Model",
  "Model Number",
  "RO Mileage",
  "Mileage Out",
  "Description",
  "Exterior Color",
  "New/Used",
  "Stock Number",
  "Transmission",
  "Engine Configuration",
  "Trim",
  "Engine Number",
  "Chassis Number",
  "License Plate Number",
  "Delivery Date",
  "Delivery Mileage",
  "In Service Date",
  "VIN Explosion Year",
  "VIN Explosion Make",
  "VIN Explosion Model",
  "VIN Explosion Trim",
  "VIN Explosion Transmission Type",
  "VIN Explosion Fuel Type",
  "VIN Explosion Engine Size",
  "VIN Explosion GVW Range",
  "Customer Number",
  "Full Name",
  "Salutation",
  "First Name",
  "Middle Name",
  "Last Name",
  "Suffix",
  "Address Line 1",
  "Address Line 2",
  "City",
  "State",
  "Zip",
  "County",
  "Home Phone",
  "Cell Phone",
  "Work Phone",
  "Work Extension",
  "Email 1",
  "Email 2",
  "Email 3",
  "Birth Date",
  "Individual/Business Flag",
  "Opt Out",
  "Block Email",
  "Block Phone",
  "Block Mail",
  "Language",
  "Customer Create Date",
  "Customer Last Activity Date",
  "CASS_STD_LINE1",
  "CASS_STD_LINE2",
  "CASS_STD_CITY",
  "CASS_STD_STATE",
  "CASS_STD_ZIP",
  "CASS_STD_ZIP4",
  "CASS_STD_DPBC",
  "CASS_STD_CHKDGT",
  "CASS_STD_CART",
  "CASS_STD_LOT",
  "CASS_STD_LOTORD",
  "CASS_STD_URB",
  "CASS_STD_FIPS",
  "CASS_STD_EWS",
  "CASS_STD_LACS",
  "CASS_STD_ZIPMOV",
  "CASS_STD_Z4LOM",
  "CASS_STD_NDIAPT",
  "CASS_STD_NDIRR",
  "CASS_STD_LACSRT",
  "CASS_STD_ERROR_CD",
]);

// Reference columns 85–122: operation / labor / parts detail block.
// Outer positions are aligned; inner values are never zipped or compacted.
export const SV_REPEATING_FIELDS = Object.freeze({
  "Operation Codes": "operation_codes",
  "Operation Code Descriptions": "operation_code_descriptions",
  "Tech Labor Line": "tech_labor_line",
  "Tech Number": "tech_number",
  "Tech Name": "tech_name",
  "Upsell": "upsell",
  "Labor Cause": "labor_cause",
  "Labor Complaint": "labor_complaint",
  "Labor Correction": "labor_correction",
  "Labor Comments": "labor_comments",
  "Recommended Operation Codes": "recommended_operation_codes",
  "Recommendations": "recommendations",
  "Operation Line Number": "operation_line_number",
  "Operation Sale Types": "operation_sale_types",
  "Operation Line Cost": "operation_line_cost",
  "Operation Line Sale": "operation_line_sale",
  "Labor Cost": "labor_cost",
  "Labor Sale": "labor_sale",
  "Parts Cost": "parts_cost",
  "Parts Sale": "parts_sale",
  "Misc Cost": "misc_cost",
  "Misc Sale": "misc_sale",
  "Gas/Oil/Grease Cost": "gas/oil/grease_cost",
  "Gas/Oil/Grease Sale": "gas/oil/grease_sale",
  "Sublet Cost": "sublet_cost",
  "Sublet Sale": "sublet_sale",
  "Labor Tech Hours": "labor_tech_hours",
  "Labor Bill Hours": "labor_bill_hours",
  "Labor Tech Rate": "labor_tech_rate",
  "Labor Bill Rate": "labor_bill_rate",
  "Parts Labor Line Number": "parts_labor_line_number",
  "Parts Line Number": "parts_line_number",
  "Parts Sale Type": "parts_sale_type",
  "Part Number": "part_number",
  "Part Description": "part_description",
  "Part Quantity": "part_quantity",
  "Parts Unit Cost": "parts_unit_cost",
  "Parts Unit Sale": "parts_unit_sale",
});
