/**
 * Static language list for the dealer "View in" translation dropdown.
 * ISO 639-1 names plus common regional variants (e.g. Swiss German, Simplified Chinese).
 * Kept in-repo so the list is identical for every lead and every browser session.
 */
export const AGENT_VIEW_LANGUAGES = [
  "(Eastern) Punjabi",
  "Abkhaz",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali, Bangla",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa, Chewa, Nyanja",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi, Dhivehi, Maldivian",
  "Dutch",
  "Dzongkha",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Fula, Fulah, Pulaar, Pular",
  "Galician",
  "Ganda",
  "Georgian",
  "German",
  "Greek (modern)",
  "Guaraní",
  "Gujarati",
  "Haitian, Haitian Creole",
  "Hausa",
  "Hebrew (modern)",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Icelandic",
  "Ido",
  "Igbo",
  "Indonesian",
  "Interlingua",
  "Interlingue",
  "Inuktitut",
  "Inupiaq",
  "Irish",
  "Italian",
  "Japanese",
  "Javanese",
  "Kalaallisut, Greenlandic",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu, Gikuyu",
  "Kinyarwanda",
  "Kirundi",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Kwanyama, Kuanyama",
  "Kyrgyz",
  "Lao",
  "Latin",
  "Latvian",
  "Limburgish, Limburgan, Limburger",
  "Lingala",
  "Lithuanian",
  "Luba-Katanga",
  "Luxembourgish, Letzeburgesch",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Manx",
  "Māori",
  "Marathi (Marāṭhī)",
  "Marshallese",
  "Mongolian",
  "Nauruan",
  "Navajo, Navaho",
  "Ndonga",
  "Nepali",
  "Northern Ndebele",
  "Northern Sami",
  "Norwegian",
  "Norwegian Bokmål",
  "Norwegian Nynorsk",
  "Nuosu",
  "Occitan",
  "Ojibwe, Ojibwa",
  "Old Church Slavonic, Church Slavonic, Old Bulgarian",
  "Oriya",
  "Oromo",
  "Ossetian, Ossetic",
  "Pāli",
  "Pashto, Pushto",
  "Persian (Farsi)",
  "Polish",
  "Portuguese",
  "Portuguese (Brazil)",
  "Portuguese (Portugal)",
  "Quechua",
  "Romanian",
  "Romansh",
  "Russian",
  "Samoan",
  "Sango",
  "Sanskrit (Saṁskṛta)",
  "Sardinian",
  "Scottish Gaelic",
  "Scottish Gaelic, Gaelic",
  "Serbian",
  "Shona",
  "Simplified Chinese",
  "Sindhi",
  "Sinhalese, Sinhala",
  "Slovak",
  "Slovene",
  "Somali",
  "Southern Ndebele",
  "Southern Sotho",
  "Spanish",
  "Standard Arabic",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Swiss German",
  "Tagalog",
  "Tahitian",
  "Tajik",
  "Tamil",
  "Tatar",
  "Telugu",
  "Thai",
  "Tibetan",
  "Tibetan Standard, Tibetan, Central",
  "Tigrinya",
  "Tonga (Tonga Islands)",
  "Tongan",
  "Traditional Chinese",
  "Tsonga",
  "Tswana",
  "Turkish",
  "Turkmen",
  "Tuvaluan",
  "Twi",
  "Ukrainian",
  "Urdu",
  "Uyghur",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Western Frisian",
  "Wolof",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang, Chuang",
  "Zulu",
];
